name: Tag and release Solr image

on:
  push:
    paths:
      - "solr/**"
      - ".github/workflows/build-solr"
    branches:
      - 'main'

env:
  SUBDIRECTORY: solr
  REGISTRY: ghcr.io
  IMAGE_NAME: goalgorilla/ci-solr

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - version: 8
            config_version: 8
          - version: 8.11
            config_version: 8
          - version: 9.1
            config_version: 9
          - version: 9.2
            config_version: 9
          - version: latest
            config_version: 9

    # There should be no need to edit below this line.
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          build-args: |
              "VERSION=${{ matrix.version }}"
              "CONFIG_VERSION=${{ matrix.config_version }}"
          context: "{{defaultContext}}:${{ env.SUBDIRECTORY }}"
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.version }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
