name: Tag and release Chrome image

on:
  push:
    paths:
      - "chrome/**"
    branches:
      - 'main'

env:
  SUBDIRECTORY: chrome
  REGISTRY: ghcr.io
  IMAGE_NAME: goalgorilla/ci-chrome

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        version:
          - 102
          - 108
          - 112
          - latest

    # There should be no need to edit below this line.
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          build-args: VERSION=${{ matrix.version }}
          context: "{{defaultContext}}:${{ env.SUBDIRECTORY }}"
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.version }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
